<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.packt.cookbook.libraries</groupId>
		<artifactId>common-libs</artifactId>
		<version>1.0-SNAPSHOT</version>
	</parent>
	<artifactId>pcl.persistence.jdbc</artifactId>

	<dependencies>
		<dependency>
			<groupId>com.packt.cookbook.libraries</groupId>
			<artifactId>common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.packt.cookbook.libraries</groupId>
			<artifactId>pcl.configurator</artifactId>
		</dependency>
		<!-- we need it here to avoid [class file for ... not found] error during mvn clean install        -->
		<dependency>
			<groupId>com.packt.cookbook.libraries</groupId>
			<artifactId>pcl.securityservice.client</artifactId>
		</dependency>
		<!-- we need it here to avoid [class file for ... not found] error during mvn clean install        -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.inject</groupId>
			<artifactId>jakarta.inject-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.ejb</groupId>
			<artifactId>jakarta.ejb-api</artifactId>
			<scope>provided</scope>
		</dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <scope>provided</scope>
        </dependency>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>